# Generated by Django 3.2.3 on 2021-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=None, max_length=1),
        ),
    ]
