# Generated by Django 3.2.3 on 2021-08-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0003_fruit_runner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
