# Generated by Django 3.2.3 on 2021-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0006_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans',
            field=models.TextField(default=None),
        ),
    ]
