# Generated by Django 3.2.3 on 2021-08-22 17:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0007_answer_ans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'), nulls_last=True)]},
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=None, max_length=3),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='django_db_p_last_na_3ad814_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='idx_first_name'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='contains_age'),
        ),
    ]
