# Generated by Django 3.2.3 on 2021-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0008_auto_20210822_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'student',
                'ordering': ['name'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=None, max_length=3),
        ),
    ]
