# Generated by Django 3.2.3 on 2021-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0010_auto_20210822_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='1900-01-01'),
        ),
    ]
