# Generated by Django 3.2.3 on 2021-08-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0014_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_db.person',),
        ),
    ]
