# Generated by Django 3.2.3 on 2021-08-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0016_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_author',
            },
        ),
        migrations.CreateModel(
            name='ShopBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('pub_date', models.DateField()),
                ('authors', models.ManyToManyField(to='django_db.ShopAuthor')),
            ],
            options={
                'db_table': 'shop_book',
            },
        ),
        migrations.CreateModel(
            name='ShopPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'shop_publisher',
            },
        ),
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('books', models.ManyToManyField(to='django_db.ShopBook')),
            ],
            options={
                'db_table': 'shop_store',
            },
        ),
        migrations.AddField(
            model_name='shopbook',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_db.shoppublisher'),
        ),
    ]
